project:
  type: website
  output-dir: docs


lang: en
website:
  title: "Containers for Computational Reproducibility"
  site-url: https://e-kotov.github.io/2024-mpidr-summer-incubator-containers/
  repo-url: https://github.com/e-kotov/2024-mpidr-summer-incubator-containers
  sidebar:
    style: "docked"
    search: true
    tools: 
      - icon: github
        text: Github
        href: https://github.com/e-kotov/2024-mpidr-summer-incubator-containers
      - icon: twitter
        text: twitter
        href: https://x.com/MPIDRnews
    contents:
      - index.qmd
      - 0-how-docker-and-binder-work.qmd
      - section: "Tasks"
        contents:
          - 1-reproducible-github-repo-in-binder.qmd
          - 2-build-docker-container-image.qmd

page-navigation: true
page-footer: 
  border: false
  left: "Copyright 2024, Egor Kotov" 
  right: 
    - icon: github
      href: https://github.com/e-kotov/2024-mpidr-summer-incubator-containers

format:
  html:
    theme:
      light: zephyr
      dark: slate
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: 4
    toc-location: right
    code-overflow: wrap
    grid:
      body-width: 800px
    mermaid:
      theme: neutral

bibliography: references.bib
bibliographystyle: mla

editor: source

editor_options:
  markdown:
    wrap: 72
    canonical: true

execute:
  freeze: auto